USE [HogwartsDB]
GO

SELECT GROUPS.NAME NAME_OF_GROUP, COURSES.NAME COURS, COUNT(*) NUMBER_OF_STUDENTS
FROM GROUPS
JOIN STUDENTS ON STUDENTS.GROUP_ID = GROUPS.GROUP_ID
JOIN COURSES ON GROUPS.COURSE_ID = COURSES.COURSE_ID
GROUP BY GROUPS.NAME, COURSES.NAME
HAVING COUNT(*) < 10
GO