USE [HogwartsDB]
GO

SELECT COURSES.NAME NAME_OF_COURS, FIRST_NAME + ' ' + LAST_NAME NAME_OF_STUDENT
FROM STUDENTS
JOIN GROUPS ON STUDENTS.GROUP_ID = GROUPS.GROUP_ID
JOIN COURSES ON GROUPS.COURSE_ID = COURSES.COURSE_ID
GO