USE [HogwartsDB]
GO

DELETE
FROM STUDENTS 
WHERE GROUP_ID 
IN (SELECT GROUP_ID 
	FROM GROUPS		
	WHERE NAME = 'SR-01')
GO

SELECT NAME NAME_OF_GROUP, FIRST_NAME, LAST_NAME
FROM GROUPS 
JOIN STUDENTS ON GROUPS.GROUP_ID = STUDENTS.GROUP_ID
GO